apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-web-be.fullname" . }}
  labels:
    {{- include "devops-web-be.labels" . | nindent 4 }}
spec:
{{/*  type: {{ .Values.service.type }}*/}}
  type: {{ .Values.serviceType }}
  ports:
    {{- range .Values.service }}
{{/*    - port: {{ .Values.service.port }}*/}}
    - port: {{ .port }}
      #targetPort: http
      targetPort: {{ .name }}
      protocol: {{ .protocol }}
      #name: http
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "devops-web-be.selectorLabels" . | nindent 4 }}
