replicaCount: 1
image:
  repository: 192.168.100.150:8082/proaimltd/devops-web-be
  pullPolicy: IfNotPresent
  tag: main-2a213eb0
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
serviceType: ClusterIP
service:
- port: 9090
  protocol: TCP
  name: http
- port: 5005
  protocol: TCP
  name: debug
- port: 9999
  protocol: TCP
  name: xxl-job
ingress:
  enabled: true
  className: ''
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 100M
    nginx.ingress.kubernetes.io/proxy-connect-timeout: 5s
    nginx.ingress.kubernetes.io/proxy-send-timeout: 20s
    nginx.ingress.kubernetes.io/proxy-read-timeout: 20s
  hosts:
  - host: test01.devops-web-be.int.mystweb.cn
    paths:
    - path: /
      pathType: ImplementationSpecific
      port: 9090
    - path: /debug
      pathType: ImplementationSpecific
      port: 5005
    - path: /xxl-job
      pathType: ImplementationSpecific
      port: 9999
  - host: test01.devops-web-fe.int.mystweb.cn
    paths:
    - path: /api
      pathType: ImplementationSpecific
      port: 9090
  tls: []
resources:
  limits:
    cpu: 1000m
    memory: 4096Mi
  requests:
    cpu: 500m
    memory: 1024Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
PARAMS: --spring.config.additional-location=classpath:/config/devops/ --spring.profiles.active=test1
es:
  hostname: elasticsearch-master.logging.svc.cluster.local
  username: elastic
  password: proaim@2013
